### ISSUE TITLE
destinationPath not work

### ISSUE THREAD

**Issue by sirkalmi** [ScottPetit/Brett#1]
Despite it, and not the "/var/mobile/Applications/blah/Library/Caches/images" destinationPath is, the files are created in the "/var/mobile/Applications/blah/Library/Caches" folder.

**Comment by sirkalmi** [comment]
My solution:

Following line:
[self writeFileDataForObject:tarFile atLocation:(location + BrettTarBlockSize) withLength:size atPath:filePath];

I changed this:
[self writeFileDataForObject:tarFile atLocation:(location + BrettTarBlockSize) withLength:size atPath:[*destinationPath stringByAppendingPathComponent:filePath.lastPathComponent]];

**Comment by ScottPetit** [comment]
Hey @sirkalmi sorry it's taken me so long to respond, my GitHub notifications were all jacked up and I only just saw this.

As far as the issue goes I think you're misusing the API to accomplish what you're doing.  Currently it's not supported to specify where the untarred file/directory will be located, it simply untars in the same place as the tar file.  The `destinationPath` parameter is meant to be used on a successful untar to locate the file and do with it what you wish (e.g. move it to the images directory).

To support this I could see Brett adding a method like `+ (BOOL)untarFileAtPath:(NSString *)filePath toPath:(NSString *)toPath withError:(NSError **)error;` where the `toPath` parameter would be @"/var/mobile/Applications/blah/Library/Caches/images" in your case.  I may get around adding this as it seems like a useful function, or you can feel free to submit a PR.
